### ISSUE TITLE
Rows with just one number are arrays with one element

### ISSUE THREAD

**Issue by maxnoe** [fact-project/zfits#3]
I think this is a bit impractical:
```
In [1]: from zfits import FactFitsCalib
In [2]: f = FactFitsCalib('20160817_016.fits.fz', '20160817_030.drs.fits.gz')
In [3]: e = next(f)
In [4]: e['EventNum']
Out[5]: array([1], dtype=int32)
```

**Comment by dneise** [comment]
It is impractical, but isn't it "better" to return a dict with all np.arrays one can ask for `shape` instead of a few numbers and a few arrays?
I mean, this way it is more homogeneous. its a map<string, np.array> and not a map <string, find_it_out_yourself>

...

**Comment by maxnoe** [comment]
I think it's principle of least surprise for `EventNum` to be an int, not an int array with one element.

**Comment by dneise** [comment]
Okay it should be an easy fix.
