### ISSUE TITLE
Support for gzipped fits

### ISSUE THREAD

**Issue by maxnoe** [fact-project/zfits#4]
would be nice to have for processing fact mc with the same reader

**Comment by dneise** [comment]
Should it really be the same reader, or could it be a `zfits.FactSimulationFile` as well? This would maybe make development easier .... after having both, we could take a look if we could merge them. 

What do you think?

Technically the `fitsio` pacakge is capable of reading vanilla `fits.gz` files out of the Box. That is .. if they really are vanilla ..

**Comment by maxnoe** [comment]
I do not want to have to check if it is data or simulation myself.

> Technically the fitsio pacakge is capable of reading vanilla fits.gz files out of the Box. That is .. if they really are vanilla ..

They *should* be. So simply first try to open it with that maybe? Or look at the magic bytes?

**Comment by maxnoe** [comment]
fixed by #6
