### ISSUE TITLE
Cython requirement seems wrong

### ISSUE THREAD

**Issue by jebuss** [fact-project/zfits#8]
when installing with pip I get an error that no package `Cython` can be found.
Should it be a small `cython` in the setup.py?

**Comment by dneise** [comment]
Dunno, might be that some names changed... I have not installed this a long time, sorry.

**Comment by dneise** [comment]
I had a look at theit github repo and this docu.
http://docs.cython.org/en/latest/src/quickstart/build.html

Both write the package name with a Capital C....

**Comment by dneise** [comment]
And I just checked it on my machine ... I can import both `Cython` and `cython` the one with the lower letter is just a 10line script which basically `from Cython import *` ... So it seems even today `Cython` is the more fundamental thing ... I have version 0.26.1 installed and I believe it comes with Anaconda.

Current version seems to be 0.27.3 according to https://docs.anaconda.com/anaconda/packages/py3.6_linux-64

**Comment by jebuss** [comment]
Mhhh.... strange. the error occured when installing zfits as a dependency in a requirements.txt with `pip install -r requirements.txt`

see: https://github.com/fact-project/EventList/blob/master/requirements.txt

**Comment by dneise** [comment]
I did not have a lot of network or time yesterday, but now I downloaded and installed the zfits repo again.
```
drwxrwxr-x  5 dneise dneise 4096 Mar 19 16:35 zfits/
dneise@lair:~/fooo/fooo$ pip install zfits/
Processing ./zfits
Requirement already satisfied: numpy>=1.12.1 in /home/dneise/anaconda3/lib/python3.6/site-packages (from zfits==0.1.1)
Requirement already satisfied: Cython>=0.25.2 in /home/dneise/anaconda3/lib/python3.6/site-packages (from zfits==0.1.1)
Requirement already satisfied: fitsio>=0.9.11 in /home/dneise/anaconda3/lib/python3.6/site-packages (from zfits==0.1.1)
Requirement already satisfied: pyfact>=0.12.1 in /home/dneise/anaconda3/lib/python3.6/site-packages (from zfits==0.1.1)
Requirement already satisfied: astropy in /home/dneise/anaconda3/lib/python3.6/site-packages (from pyfact>=0.12.1->zfits==0.1.1)
[... more of these "Requirement already satisfied" ... ]
Installing collected packages: zfits
  Running setup.py install for zfits ... done
Successfully installed zfits-0.1.1
```

So we have the "but it works on my machine"-effect going on here? ... damn

**Comment by dneise** [comment]
Okay another try:

fresh environment: `conda create -n myenv python=3.6 pip`
`source activate myenv`
plust numpy and scipy, so that these are not pip-installed and it goes faster.
`conda install numpy scipy`

```
(myenv) dneise@lair:~/fooo/bar$ conda list
# packages in environment at /home/dneise/anaconda3/envs/myenv:
#
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2018.1.18                py36_0  
intel-openmp              2018.0.0             hc7b2577_8  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libstdcxx-ng              7.2.0                hdf63c60_3  
mkl                       2018.0.1             h19d6760_4  
ncurses                   6.0                  h9df7e31_2  
numpy                     1.14.2           py36hdbf6ddf_0  
openssl                   1.0.2n               hb7f436b_0  
pip                       9.0.1                    py36_5  
python                    3.6.4                hc3d631a_3  
readline                  7.0                  ha6073c6_4  
scipy                     1.0.0            py36hbf646e7_0  
setuptools                38.5.1                   py36_0  
sqlite                    3.22.0               h1bed415_0  
tk                        8.6.7                hc745277_3  
wheel                     0.30.0           py36hfd4bba0_1  
xz                        5.2.3                h55aa19d_2  
zlib                      1.2.11               ha838bed_2  
```

now .. just as the requirements.txt does it:
`pip install -e git://github.com/fact-project/zfits.git#egg=zfits`

Does not work here in my place .. connection refused ... seems some ports are blocked or so. So I'll download and installed separately 
`git clone https://github.com/fact-project/zfits` and then

```
(myenv) dneise@lair:~/fooo/bar$ pip install -e zfits/
Obtaining file:///home/dneise/fooo/bar/zfits
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dneise/fooo/bar/zfits/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

aha confirmed

**Comment by dneise** [comment]
okay so the traceback shows the source of the problem clearly. 

in line 3, i.e. **before** the `setup()`-function is even started ... setup.py tries to import from Cython. So of course no "install_requires" has even started to be resolved... this is more a "setup_requires" type of thing.

No time left to solve it ... gotta google some stuff.

But you can solve it for your case at the moment.... simply install cython manually on your system on try again.

**Comment by jebuss** [comment]
Thanks for your help. We will do so!
